version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    env_file: .env
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${PORT_H}:${PORT_C}/tcp
    networks:
      - front_net
  post:
    env_file: .env
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - back_net
      - front_net
  comment:
    env_file: .env
    image: ${USERNAME}/comment:${COM_VER}
    networks:
      - back_net
      - front_net
  
  
volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
