version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    env_file: .env
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USERNAME}/ui:logging
    ports:
      - ${PORT_H}:${PORT_C}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    env_file: .env
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USERNAME}/post:logging
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    env_file: .env
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${USERNAME}/comment:logging
    networks:
      - back_net
      - front_net
  
  
volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
